import { RISK_META, STATUS_META } from "@/lib/risk";
import { formatBytes, formatDate } from "@/lib/utils";
import type { InvestigationRecord } from "@/lib/types";

/** Renders a case as a portable Markdown report. Pure — safe on either side. */
export function buildMarkdownReport(record: InvestigationRecord): string {
  const r = record.result;
  if (!r) return `# ${record.title}\n\nThis investigation has not completed.\n`;

  const meta = RISK_META[r.riskLevel];
  const lines: string[] = [];

  lines.push(`# Compliance investigation report`);
  lines.push("");
  lines.push(`**Case**  ${record.reference}`);
  lines.push(`**Title**  ${record.title}`);
  if (record.subject) lines.push(`**Counterparty**  ${record.subject}`);
  lines.push(`**Opened**  ${formatDate(record.createdAt)}`);
  if (record.completedAt) lines.push(`**Completed**  ${formatDate(record.completedAt)}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  lines.push(`## Verdict`);
  lines.push("");
  lines.push(`- **Fraud risk** ${r.riskScore}/100 — ${meta.label}`);
  lines.push(`- **Confidence** ${r.confidence}%`);
  lines.push(
    `- **Controls** ${r.metrics.passed} passed · ${r.metrics.warnings} warnings · ${r.metrics.failures} failed`,
  );
  if (r.metrics.exposure > 0) {
    lines.push(
      `- **Exposure** ₹${r.metrics.exposure.toLocaleString("en-IN")} behind open exceptions`,
    );
  }
  lines.push("");
  lines.push(r.summary);
  lines.push("");

  lines.push(`## Recommended actions`);
  lines.push("");
  r.actions.forEach((a, i) => {
    lines.push(`${i + 1}. **${a.title}** _(${a.priority.replace("-", " ")})_`);
    lines.push(`   ${a.detail}`);
  });
  lines.push("");

  lines.push(`## Findings`);
  lines.push("");
  lines.push(`| # | Control | Category | Outcome | Evidence |`);
  lines.push(`|---|---------|----------|---------|----------|`);
  r.findings.forEach((f, i) => {
    lines.push(
      `| ${i + 1} | ${f.label} | ${f.category} | ${STATUS_META[f.status].label} | \`${f.evidence}\` |`,
    );
  });
  lines.push("");

  r.findings
    .filter((f) => f.status !== "pass")
    .forEach((f) => {
      lines.push(`### ${STATUS_META[f.status].label} · ${f.code} — ${f.label}`);
      lines.push("");
      lines.push(f.detail);
      lines.push("");
      lines.push(`> Evidence: \`${f.evidence}\` · Source: ${f.source} · Weight ${f.weight}/10`);
      lines.push("");
    });

  lines.push(`## Extracted fields`);
  lines.push("");
  r.ledger.forEach((row) => lines.push(`- **${row.label}** — ${row.value}`));
  lines.push("");

  lines.push(`## Evidence in scope`);
  lines.push("");
  record.documents.forEach((d) => {
    lines.push(`- \`${d.name}\` — ${d.docType}, ${formatBytes(d.size)}, ${d.fingerprint}`);
  });
  lines.push("");

  if (record.notes) {
    lines.push(`## Analyst context`);
    lines.push("");
    lines.push(record.notes);
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(
    `_Generated by Veritas · run ${r.seed.slice(0, 18)} · ${r.metrics.checksRun} controls in ${(r.metrics.processingMs / 1000).toFixed(1)}s._`,
  );
  lines.push(
    `_Demo build: findings are simulated and must not be relied on for a real filing._`,
  );

  return lines.join("\n");
}

export function reportFileName(record: InvestigationRecord): string {
  const slug = record.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 48);
  return `${record.reference}-${slug || "report"}.md`;
}
